### ISSUE TITLE
Name and Hostname should be used

### ISSUE THREAD

**Issue by bcjmk** [wicol/unifi-dns#11]
The NAME only seems to appear with an Alias defined. Would be helpful to enable the "Hostname" entry as an option. At least in the initial runs it can be used to help identify unknown items. Not all my bulbs and other devices are reporting correctly.

Nice work. I'm modifying the script to add a log.warn which provides details on each device to help me figure out what some of them are.

**Comment by wicol** [comment]
Yeah, could be configurable I guess! Feel free to make a PR :)
