### ISSUE TITLE
Nice! Could this be run as an onboot script?

### ISSUE THREAD

**Issue by JohnGalt1717** [wicol/unifi-dns#9]
Per here: https://github.com/boostchicken/udm-utilities/tree/master/on-boot-script

Would it be possible to just change this to an onboot script and store the files on the device so that it doesn't have to run as a docker image? My understanding is that this persists until firmeware update and the on boot script stuff runs automatically on every restart.

Would be an awesome and simple way to make this work...

**Comment by wicol** [comment]
I don't know much about the UDM, but if it has or can install all the dependencies (python, dnsmasq) I guess it would be possible, sure.
